language: go
go:
- 1.10.x
install:
- go get gopkg.in/alecthomas/gometalinter.v1
- go get github.com/gordonklaus/ineffassign
- go get github.com/jgautheron/goconst/cmd/goconst
- go get github.com/kisielk/errcheck
- go get golang.org/x/lint/golint
- go get github.com/golang/dep/cmd/dep
script:
- gometalinter.v1 --vendor --disable-all --enable=vet --enable=golint --enable=ineffassign
  --enable=goconst --tests ./...
before_deploy:
- go get github.com/goreleaser/goreleaser
deploy:
  skip_cleanup: true
  provider: script
  script: goreleaser
  on:
    tags: true
env:
  global:
    secure: Ro4/EJH4ACcYc5z0nsk36vn5g1nKe1MRiXDxc7lcY6byY3jrBZiY0sIcAh03C+PYxZGdMBp35+Y93oq9f4REzZkbNI1vToW+df+M/nJ320CHSoSToXUxUZr5FhOYbVvg8ERZIl8iz6wfF/p2j83xWYnSRM1mMLyUtAtgaG/QcVJeKiaaw6eL6K/nbpvNo/lyYsStc6d7WiqO2cKk5AoAqBk0GGagKwv4t23zi6YpRDCuKqqXmQqUb5Y8dKvTC0iTgur3UDeJffBvZtyKwUTZqS8IDJzD2RxkpAqUsnhOIqnrFTUZEJAUkdiTaL0gDqVbb+JHrdBwhHZRP1uLKBRgCbYR17412/Zk+GvQ8BjvJeWYjOPhm2I0LDqkieLhF6I20QGRI5d5pVG1Mn8ocsgHw8lbAfN41MlW7Khq/oLXntFjn5FE2X1KQ7fB9rZDZViaUzDJYXKz3dEd/aatwHr93LWpkDoOqlVfP1QqkPFEZ1OyYJKg9XhbOV0vbv1hpWvcdlcaBw19nW7yXJgeArUm1WLmLFBvvXqBTsBSVMtbQrnhwDgakur4mqCf4e27nMcSzx5vqJT21JvHKsByybL1vKRNcRj+921Pluh+KhlXuyObrGM2FM7OGuACfiG7/rwP81MZtgKUvYSNqpci+ybJkxrql+e+bqVEjUM6BtENE+k=
